services:
  # Backend API Service
  - type: web
    name: ecg-intelligence-api
    runtime: node
    repo: https://github.com/nbrain-team/ecg
    branch: main
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ecg-intelligence-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://ecg-intelligence-app.onrender.com

  # Frontend Service - Static Site
  - type: web
    name: ecg-intelligence-app
    runtime: static
    repo: https://github.com/nbrain-team/ecg
    branch: main
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://ecg-intelligence-api.onrender.com

databases:
  # PostgreSQL Database
  - name: ecg-intelligence-db
    databaseName: ecg_intelligence
    user: ecg_admin
    postgresMajorVersion: 15 